# Generated by Django 2.0 on 2018-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbox', '0002_auto_20180903_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
