# Generated by Django 2.0 on 2018-09-11 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180817_1335'),
        ('gmailbox', '0003_auto_20180906_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mail_type',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='sender',
        ),
        migrations.AddField(
            model_name='mail',
            name='recipient_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='snippet',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.RemoveField(
            model_name='mail',
            name='contact',
        ),
        migrations.AddField(
            model_name='mail',
            name='contact',
            field=models.ManyToManyField(blank=True, to='accounts.Contact'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Matter'),
        ),
        migrations.RemoveField(
            model_name='mail',
            name='organisation',
        ),
        migrations.AddField(
            model_name='mail',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='accounts.Organisation'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
