# Generated by Django 2.0 on 2018-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbox', '0006_mail_gmail_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailaccount',
            name='address',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
