# Generated by Django 2.0 on 2018-09-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbox', '0007_auto_20180912_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ('-date',)},
        ),
    ]
