# Generated by Django 2.0 on 2018-09-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbox', '0008_auto_20180914_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
