# Generated by Django 2.0 on 2018-09-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbox', '0009_mail_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(blank=True, null=True, upload_to='attachments/')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(blank=True, max_length=10, null=True)),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gmailbox.Mail')),
            ],
        ),
    ]
