# Generated by Django 2.0 on 2018-10-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbox', '0012_auto_20181009_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
