# Generated by Django 2.0 on 2018-11-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailbox', '0013_auto_20181024_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='inline',
            field=models.BooleanField(default=False),
        ),
    ]
