# Generated by Django 2.0 on 2018-07-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(1, 'Original held by Andreyev Lawyers'), (2, 'Removed'), (3, 'Not Returned'), (4, 'Transit Money held by Andreyev Lawyers'), (5, 'Scanned')], null=True),
        ),
    ]
