# Generated by Django 2.0 on 2018-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180719_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='reference',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
