# Generated by Django 2.0 on 2018-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_office_xero_branding_theme_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Matter statuses',
            },
        ),
    ]
