# Generated by Django 2.0 on 2018-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timeentrytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.IntegerField(choices=[(1, 'Time Entry'), (2, 'Disbursement'), (3, 'Fixed Price Item')])),
                ('gst_status', models.IntegerField(choices=[(1, 'GST (10%)'), (2, 'GST Export (0%)'), (3, 'BAS Excluded (0%)')])),
                ('account_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Account numbers',
            },
        ),
    ]
