# Generated by Django 2.0 on 2018-09-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180914_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountnumber',
            options={'ordering': ('entry_type', 'gst_status'), 'verbose_name_plural': 'Account numbers'},
        ),
    ]
