# Generated by Django 2.0 on 2018-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180914_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='reference',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
