# Generated by Django 2.0 on 2018-07-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='xero_invoice_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xero_invoice_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
