# Generated by Django 2.0 on 2018-08-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.IntegerField(choices=[(1, 'EFT'), (2, 'BPAY'), (3, 'Credit Card'), (4, 'Cheque'), (5, 'Trust Account'), (6, 'Trust Clearing Account'), (7, 'Cash'), (8, 'Write Off')], null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.IntegerField(choices=[(1, 'EFT'), (2, 'BPAY'), (3, 'Credit Card'), (4, 'Cheque'), (5, 'Trust Account'), (6, 'Trust Clearing Account'), (7, 'Cash'), (8, 'Write Off')], null=True),
        ),
    ]
