# Generated by Django 2.0 on 2018-08-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20180730_0137'),
        ('invoicing', '0002_auto_20180803_0840'),
    ]

    operations = [
    ]
