# Generated by Django 2.0 on 2018-08-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_merge_20180807_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='is_invoice_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_invoice_paid',
            field=models.BooleanField(default=True),
        ),
    ]
