# Generated by Django 2.0 on 2018-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20180810_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='xero_invoice_id',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='xero_invoice_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
