# Generated by Django 2.0 on 2018-07-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=256, null=True, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(max_length=256, null=True, verbose_name='Consumer Secret')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
