# Generated by Django 2.0 on 2018-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xero',
            name='rsa_key',
            field=models.TextField(null=True, verbose_name='RSA Key'),
        ),
    ]
