# Generated by Django 2.0 on 2018-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_xero_rsa_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=256, null=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=256, null=True, verbose_name='Client Secret')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
