# Generated by Django 2.0 on 2018-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmail',
            name='show_mails',
            field=models.BooleanField(default=True),
        ),
    ]
