# Generated by Django 2.0 on 2018-07-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='core.Industry'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation', to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='postal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_postal', to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='_spouses',
            field=models.ManyToManyField(blank=True, related_name='_contact__spouses_+', to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='occupation',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Occupation'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='accounts.Organisation'),
        ),
        migrations.AddField(
            model_name='contact',
            name='postal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_postal', to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrers', to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.Office'),
        ),
        migrations.AddField(
            model_name='client',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='accounts.Organisation'),
        ),
        migrations.AddField(
            model_name='client',
            name='second_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_clients', to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_postal', to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
