# Generated by Django 2.0 on 2018-07-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180717_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='xero_contact_id',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
