# Generated by Django 2.0 on 2018-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180717_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_legal',
            field=models.BooleanField(default=False),
        ),
    ]
