# Generated by Django 2.0 on 2018-08-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_xero_contact_id'),
        ('accounts', '0003_user_is_legal'),
    ]

    operations = [
    ]
