# Generated by Django 2.0 on 2018-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20180807_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='xero_contact_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
