# Generated by Django 2.0 on 2018-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180810_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='xero_contact_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
