# Generated by Django 2.0 on 2018-09-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180817_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='xero_contact_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
