# Generated by Django 2.0 on 2018-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180913_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='show_mails',
            field=models.BooleanField(default=True),
        ),
    ]
