# Generated by Django 2.0 on 2018-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contact_show_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
