# Generated by Django 2.0 on 2018-09-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contact_show_mails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='show_mails',
        ),
    ]
