# Generated by Django 2.0 on 2018-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_contact_show_mails'),
        ('accounts', '0009_contact_place_of_birth'),
    ]

    operations = [
    ]
