# Generated by Django 2.0 on 2019-01-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20180920_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link_mails',
            field=models.BooleanField(default=True),
        ),
    ]
