# Generated by Django 2.0 on 2019-01-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contact_link_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='link_mails',
            field=models.BooleanField(default=True),
        ),
    ]
