# Generated by Django 2.0 on 2018-07-17 15:34

import sitename.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180717_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMatter',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('conflict_status', models.IntegerField(choices=[(1, 'Outstanding'), (2, 'No other parties'), (3, 'Complete')])),
                ('conflict_parties', models.TextField(null=True)),
                ('created_date', models.DateField()),
                ('closed_date', models.DateField(null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_method', models.IntegerField(choices=[(1, 'Fixed price'), (2, 'Time Entry')])),
                ('billable_status', models.IntegerField(choices=[(1, 'Open'), (2, 'Suspended'), (3, 'Closed')])),
                ('funds_in_trust', models.BooleanField(default=False)),
                ('matter_status', models.IntegerField(choices=[(1, 'Active - High (70+ units)'), (2, 'Active - Moderate (30-70 units)'), (3, 'Active - Low (0-30 units)'), (4, 'Waiting for Internal review'), (5, 'Waiting for AA review'), (6, 'Waiting for external party to respond'), (7, 'Ad hoc Work'), (8, 'Need to be billed'), (9, 'Matter Closed'), (10, 'Business Building')], default=3)),
                ('file_path', models.CharField(blank=True, max_length=250, null=True)),
                ('conflict_check_sent', models.CharField(blank=True, max_length=100, null=True)),
                ('is_conflict_check_sent', models.BooleanField(default=False)),
                ('standard_terms_sent', models.CharField(blank=True, max_length=100, null=True)),
                ('is_standard_terms_sent', models.BooleanField(default=False)),
                ('referrer_thanked', models.CharField(blank=True, max_length=100, null=True)),
                ('is_referrer_thanked', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical matter',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('conflict_status', models.IntegerField(choices=[(1, 'Outstanding'), (2, 'No other parties'), (3, 'Complete')])),
                ('conflict_parties', models.TextField(null=True)),
                ('created_date', models.DateField()),
                ('closed_date', models.DateField(null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_method', models.IntegerField(choices=[(1, 'Fixed price'), (2, 'Time Entry')])),
                ('billable_status', models.IntegerField(choices=[(1, 'Open'), (2, 'Suspended'), (3, 'Closed')])),
                ('funds_in_trust', models.BooleanField(default=False)),
                ('matter_status', models.IntegerField(choices=[(1, 'Active - High (70+ units)'), (2, 'Active - Moderate (30-70 units)'), (3, 'Active - Low (0-30 units)'), (4, 'Waiting for Internal review'), (5, 'Waiting for AA review'), (6, 'Waiting for external party to respond'), (7, 'Ad hoc Work'), (8, 'Need to be billed'), (9, 'Matter Closed'), (10, 'Business Building')], default=3)),
                ('file_path', models.CharField(blank=True, max_length=250, null=True)),
                ('conflict_check_sent', models.CharField(blank=True, max_length=100, null=True)),
                ('is_conflict_check_sent', models.BooleanField(default=False)),
                ('standard_terms_sent', models.CharField(blank=True, max_length=100, null=True)),
                ('is_standard_terms_sent', models.BooleanField(default=False)),
                ('referrer_thanked', models.CharField(blank=True, max_length=100, null=True)),
                ('is_referrer_thanked', models.BooleanField(default=False)),
            ],
            bases=(models.Model, sitename.mixins.UpdateAttributesMixin),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StandartDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('description', models.TextField()),
                ('cost', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Standard Disbursement',
                'verbose_name_plural': 'Standard Disbursements',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('units', models.FloatField()),
                ('units_to_bill', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Billable'), (2, 'Non billable')], null=True)),
                ('gst_status', models.IntegerField(choices=[(1, 'GST (10%)'), (2, 'GST Export (0%)'), (3, 'BAS Excluded (0%)')], null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('entry_type', models.IntegerField(choices=[(1, 'Time Entry'), (2, 'Disbursement'), (3, 'Fixed Price Item')])),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='accounts.Client')),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
                'ordering': ['date'],
            },
            bases=(models.Model, sitename.mixins.UpdateAttributesMixin),
        ),
    ]
