# Generated by Django 2.0 on 2018-07-17 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
        ('accounts', '0002_auto_20180717_1534'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='invoicing.Invoice'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='billing.Matter'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='billing.Matter'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matter',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_of_matters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matter',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='accounts.Client'),
        ),
        migrations.AddField(
            model_name='matter',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_matters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matter',
            name='matter_sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='core.MatterSubType'),
        ),
        migrations.AddField(
            model_name='matter',
            name='matter_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='core.MatterType'),
        ),
        migrations.AddField(
            model_name='matter',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_of_matters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='assistant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Client'),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='matter_sub_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.MatterSubType'),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='matter_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.MatterType'),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='principal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
