# Generated by Django 2.0 on 2018-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180717_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartdisbursement',
            name='gst_status',
            field=models.IntegerField(choices=[(1, 'GST (10%)'), (2, 'GST Export (0%)'), (3, 'BAS Excluded (0%)')], null=True),
        ),
    ]
