# Generated by Django 2.0 on 2018-07-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180717_1534'),
        ('billing', '0003_standartdisbursement_gst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.Contact'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='billing.Matter'),
        ),
    ]
