# Generated by Django 2.0 on 2018-07-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180724_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='invoicing.Invoice'),
        ),
    ]
