# Generated by Django 2.0 on 2018-08-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180726_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatter',
            name='matter_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.MatterStatus'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.MatterStatus'),
        ),
    ]
