# Generated by Django 2.0 on 2018-09-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_leadstatus'),
        ('billing', '0007_entrytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='entry_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.EntryType'),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='lead_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='lead_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.LeadStatus'),
        ),
        migrations.AddField(
            model_name='matter',
            name='entry_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.EntryType'),
        ),
        migrations.AddField(
            model_name='matter',
            name='lead_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='lead_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.LeadStatus'),
        ),
    ]
