# Generated by Django 2.0 on 2018-09-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timeentrytype'),
        ('billing', '0008_auto_20180910_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='time_entry_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.TimeEntryType'),
        ),
    ]
