# Generated by Django 2.0 on 2018-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_timeentry_time_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatter',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
