# Generated by Django 2.0 on 2018-10-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20180929_0215'),
        ('billing', '0010_auto_20181001_2219'),
    ]

    operations = [
    ]
